<option value="1">ABRA</option>
<option value="2">AGUSAN DEL NORTE</option>
<option value="3">AGUSAN DEL SUR</option>
<option value="4">AKLAN</option>
<option value="5">ALBAY</option>
<option value="6">ANTIQUE</option>
<option value="7">APAYAO</option>
<option value="8">AURORA</option>
<option value="9">BASILAN</option>
<option value="10">BATAAN</option>
<option value="11">BATANES</option>
<option value="12">BATANGAS</option>
<option value="13">BENGUET</option>
<option value="14">BILIRAN</option>
<option value="15">BOHOL</option>
<option value="16">BUKIDNON</option>
<option value="17">BULACAN</option>
<option value="18">CAGAYAN</option>
<option value="19">CAMARINES NORTE</option>
<option value="20">CAMARINES SUR</option>
<option value="21">CAMIGUIN</option>
<option value="22">CAPIZ</option>
<option value="23">CATANDUANES</option>
<option value="24">CAVITE</option>
<option value="25">CEBU</option>
<option value="26">COMPOSTELA VALLEY</option>
<option value="27">DAVAO DEL NORTE</option>
<option value="28">DAVAO DEL SUR</option>
<option value="29">DAVAO OCCIDENTAL</option>
<option value="30">DAVAO ORIENTAL</option>
<option value="31">EASTERN SAMAR</option>
<option value="32">GUIMARAS</option>
<option value="33">IFUGAO</option>
<option value="34">ILOCOS NORTE</option>
<option value="35">ILOCOS SUR</option>
<option value="36">ILOILO</option>
<option value="37">ISABELA</option>
<option value="38">KALINGA</option>
<option value="39">KALINGA APAYAO</option>
<option value="40">LA UNION</option>
<option value="41">LAGUNA</option>
<option value="42">LANAO DEL NORTE</option>
<option value="43">LANAO DEL SUR</option>
<option value="44">LEYTE</option>
<option value="45">MAGUINDANAO</option>
<option value="46">MARINDUQUE</option>
<option value="47">MASBATE</option>
<option value="48">METRO MANILA </option>
<option value="49">MISAMIS OCCIDENTAL</option>
<option value="50">MISAMIS ORIENTAL</option>
<option value="51">MOUNTAIN PROVINCE</option>
<option value="52">NEGROS OCCIDENTAL</option>
<option value="53">NEGROS ORIENTAL</option>
<option value="54">NORTH COTABATO</option>
<option value="55">NORTHERN SAMAR</option>
<option value="56">NUEVA ECIJA</option>
<option value="57">NUEVA VIZCAYA</option>
<option value="58">OCCIDENTAL MINDORO</option>
<option value="59">ORIENTAL MINDORO</option>
<option value="60">PALAWAN</option>
<option value="61">PAMPANGA</option>
<option value="62">PANGASINAN</option>
<option value="63">QUEZON</option>
<option value="64">QUIRINO</option>
<option value="65">RIZAL</option>
<option value="66">ROMBLON</option>
<option value="67">SARANGANI</option>
<option value="68">SHARIFF KABUNSUAN</option>
<option value="69">SIQUIJOR</option>
<option value="70">SORSOGON</option>
<option value="71">SORSOGON CITY</option>
<option value="72">SOUTH COTABATO</option>
<option value="73">SOUTHERN LEYTE</option>
<option value="74">SULTAN KUDARAT</option>
<option value="75">SULU</option>
<option value="76">SURIGAO DEL NORTE</option>
<option value="77">SURIGAO DEL SUR</option>
<option value="78">TARLAC</option>
<option value="79">TAWI TAWI</option>
<option value="80">TAYABAS</option>
<option value="81">WESTERN SAMAR</option>
<option value="82">ZAMBALES</option>
<option value="83">ZAMBOANGA DEL NORTE</option>
<option value="84">ZAMBOANGA DEL SUR</option>
<option value="85">ZAMBOANGA SIBUGAY</option>